spring.application.name=AddressBookWorkshop
spring.datasource.url=jdbc:mysql://localhost:3306/addressbook_db
spring.datasource.username=root
spring.datasource.password=Jagratidixit@5600
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#jwt secret key
jwt.secret= qwBuSpBiT+tCRRNdA9G+uj0xCHWW2eqHkAEmmiCNL8Y=
